name: "Validate Resume"
description: "Validates JSON Resume files using resume-cli"
inputs:
  resume-path:
    description: "Path to the resume JSON file"
    required: true
runs:
  using: "composite"
  steps:
    - uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@c9d9d041ba4ef35695ee469c4782fa6a8bbebbcc # 0.21.2
      with:
        working-directory: ${{ github.action_path }}

    - name: Validate resume
      id: validate
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        NODE_PATH: ${{ github.action_path }}/node_modules
        ACTION_PATH: ${{ github.action_path }}
        RESUME_PATH: ${{ inputs.resume-path }}
      with:
        script: |
          const path = require('node:path');
          const fs = require('node:fs');

          let resumePath = process.env.RESUME_PATH;
          if (!resumePath) {
            throw new Error('Resume path is not provided.');
          }
          resumePath = path.resolve(resumePath);
          if (!fs.existsSync(resumePath)) {
            throw new Error(`Resume file does not exist at path: ${resumePath}`);
          }

          await exec.exec('npm', ['run', 'validate', '--', resumePath], {
            cwd: process.env.ACTION_PATH,
          });
