root: true
env:
  browser: true
  node: true
  es2023: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
  n/no-missing-import: off
