name: "Generate Resume PDF"
description: "Generates PDF from JSON Resume file using resume-cli"
inputs:
  resume-path:
    description: "Path to the resume JSON file"
    required: true
  output-path:
    description: "Path where the PDF should be generated"
    required: true
runs:
  using: "composite"
  steps:
    # jscpd:ignore-start
    - uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@32a69b7b8fd5f7ab7bf656e7e88aa90ad235cf8d # 0.18.0
      with:
        working-directory: ${{ github.action_path }}

    - name: Validate resume
      id: validate
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        NODE_PATH: ${{ github.action_path }}/node_modules
        ACTION_PATH: ${{ github.action_path }}
        RESUME_PATH: ${{ inputs.resume-path }}
        OUTPUT_PATH: ${{ inputs.output-path }}
      with:
        script: |
          const path = require('node:path');
          const fs = require('node:fs');

          let resumePath = process.env.RESUME_PATH;
          if (!resumePath) {
            throw new Error('Resume path is not provided.');
          }

          resumePath = path.resolve(resumePath);
          if (!fs.existsSync(resumePath)) {
            throw new Error(`Resume file does not exist at path: ${resumePath}`);
          }

          let outputPath = process.env.OUTPUT_PATH;
          if (!outputPath) {
            throw new Error('Output path is not provided.');
          }
          outputPath = path.resolve(outputPath);
          if (!fs.existsSync(path.dirname(outputPath))) {
            throw new Error(`Output directory does not exist: ${path.dirname(outputPath)}`);
          }

          await exec.getExecOutput('npm', ['run', 'generate-pdf', '--', resumePath, outputPath], { cwd: process.env.ACTION_PATH });
    # jscpd:ignore-end
